// Système multi-langue pour Luxio
const translations = {
    fr: {
        // Navigation et interface
        'help': 'Aide',
        'support': 'Support',
        'contact': 'Contact',
        'call_us': 'Appelez-nous:',
        'my_dashboard': 'Mon Tableau de Bord',
        'login': 'Connexion',
        'wishlist': 'Liste de Souhaits',
        'my_cart': 'Mon Panier',
        'notifications': 'Notifications',
        'account_settings': 'Paramètres du Compte',
        'my_account': 'Mon Compte',
        'logout': 'Déconnexion',
        'search_placeholder': 'Que cherchez-vous?',
        'all_category': 'Toutes Catégories',
        'home': 'Accueil',
        'shop': 'Boutique',
        'single_page': 'Page Produit',
        'pages': 'Pages',
        'smartphones': 'Smartphones',
        'electronics': 'Électronique',
        'currency': 'EUR',
        'language': 'Français',
        'add_to_cart': 'Ajouter au Panier',
        'buy_now': 'Acheter Maintenant',
        'price': 'Prix',
        'brand': 'Marque',
        'model': 'Modèle',
        'storage': 'Stockage',
        'view_details': 'Voir Détails',
        'cart_total': 'Total Panier',
        'watches': 'Montres',
        'fashion': 'Mode',
        'discover': 'Découvrir',
        'view_collections': 'Voir Collections',
        'satisfied_customers': 'Clients Satisfaits',
        'positive_reviews': 'Avis Positifs',
        'express_delivery': 'Livraison Express',
        'popular_products': 'Produits Populaires',
        'all': 'Tous',
        'accessories': 'Accessoires',
        'new_arrivals': 'Nouveautés',
        'load_more': 'Voir Plus de Produits',
        'discover_excellence': 'Découvrez l\'Excellence',
        'home_living': 'Maison',
        'mobility': 'Mobilité',
        'services': 'Services',
        'more': '+ Plus',
        'free_delivery': 'Livraison Gratuite',
        'premium_warranty': 'Garantie Premium',
        'up_to_discount': 'Jusqu\'à -40%',
        'premium_collection_2025': 'COLLECTION PREMIUM 2025',
        'hero_description': 'Technologie de pointe, design raffiné, expérience exceptionnelle. Découvrez notre sélection exclusive de produits haut de gamme.',
        'delivery_24h': 'Livraison 24h',
        'warranty_2_years': 'Garantie 2 ans',
        'rating_4_9': 'Note 4.9/5',
        'explore_by_category': 'Explorer par Catégorie',
        'latest_tech': 'Dernières technologies',
        'connected_classic': 'Connectées & classiques',
        'premium_sound': 'Son premium',
        'innovation_design': 'Innovation & design',
        '120_products': '120+ produits',
        '80_products': '80+ produits',
        '150_products': '150+ produits',
        '200_products': '200+ produits',
        'audio': 'Audio',
        'tech': 'Tech',
        'stay_connected': 'Restez connecté avec LUXIO',
        'newsletter_description': 'Découvrez en avant-première nos nouveautés et offres exclusives',
        'email_placeholder': 'Votre adresse email',
        'subscribe': 'S\'abonner',
        'product_iphone_15': 'iPhone 15 Pro Max',
        // Cart and shopping
        'cart': 'Panier',
        'your_cart': 'Votre Panier',
        'cart_description': 'Finalisez votre commande et profitez de la livraison gratuite',
        'cart_empty': 'Votre panier est vide',
        'cart_empty_description': 'Découvrez notre collection premium et ajoutez vos produits favoris',
        'discover_products': 'Découvrir nos Produits',
        'product': 'Produit',
        'quantity': 'Quantité',
        'total': 'Total',
        'actions': 'Actions',
        'view_cart': 'Voir Panier',
        'order': 'Commander',
        'continue_shopping': 'Continuer les Achats',
        'proceed_to_payment': 'Procéder au Paiement',
        'added_to_cart': 'ajouté au panier!',
        'and_more_items': 'et ${count} autres articles...',
        'remove': 'Supprimer',
        'subtotal': 'Sous-total',
        'delivery': 'Livraison',
        'free': 'Gratuite',
        'tax_vat': 'TVA (20%)',
        'summary_title': 'Récapitulatif',
        'finalize_order': 'Finaliser votre Commande',
        'order_summary': 'Résumé de Commande',
        'shipping_info': 'Informations de Livraison',
        'payment_method': 'Moyen de Paiement',
        'place_order': 'Passer la Commande',
        // Additional cart and checkout elements
        'promo_placeholder': 'Code promo',
        'apply_promo': 'Appliquer',
        'finalize_order_btn': 'Finaliser la Commande',
        'continue_shopping_btn': 'Continuer les Achats',
        'secure_payment': 'Paiement Sécurisé',
        'free_returns': 'Retour Gratuit',
        'you_might_like': 'Vous pourriez aussi aimer',
        'payment_breadcrumb': 'Paiement',
        'choose_payment_method': 'Choisissez votre méthode de paiement sécurisée',
        'payment_methods': 'Méthodes de Paiement',
        'order_summary_checkout': 'Récapitulatif de la Commande',
        'empty_cart_item': 'Panier vide',
        'security_guarantees': 'Sécurité & Garanties',
        'payment_100_secure': 'Paiement 100% sécurisé',
        'express_delivery_24h': 'Livraison Express 24h',
        'free_returns_30days': 'Retour gratuit 30 jours',
        // Footer
        'footer_brand_description': 'Innovation et excellence depuis 2020',
        'footer_products': 'Produits',
        'footer_support': 'Support',
        'footer_company': 'Entreprise',
        'footer_help_center': 'Centre d\'aide',
        'footer_warranty': 'Garantie',
        'footer_returns': 'Retours',
        'footer_about': 'À propos',
        'footer_careers': 'Carrières',
        'footer_press': 'Presse',
        'footer_partners': 'Partenaires',
        'footer_copyright': '© 2025 LUXIO. Tous droits réservés.',
        'footer_terms': 'Conditions',
        'footer_privacy': 'Confidentialité',
        'footer_cookies': 'Cookies',
        // Payment methods
        'bank_transfer': 'Virement Bancaire',
        'bank_transfer_desc': 'Paiement sécurisé par virement bancaire - Traitement sous 24-48h',
        'tickets_payment': 'Tickets Transcash & PCS',
        'tickets_payment_desc': 'Paiement par tickets prépayés - Disponibles sur recharge.com',
        'cryptocurrency': 'Cryptomonnaie',
        'reference_code_required': 'Code de référence obligatoire :',
        'use_code_as_reference': 'Utilisez ce code comme motif de virement pour identifier votre commande',
        'bank_details': 'Coordonnées Bancaires',
        'instructions': 'Instructions :',
        'bank_instruction_1': 'Effectuez le virement avec le montant exact de votre commande',
        'bank_instruction_2': 'Utilisez le code de référence comme motif de virement',
        'bank_instruction_3': 'Votre commande sera traitée dès réception du paiement (24-48h)',
        'bank_instruction_4': 'Vous recevrez une confirmation par email',
        'confirm_bank_transfer': 'Confirmer le Virement Bancaire',
        'reference_code_for_purchase': 'Code de référence pour votre achat :',
        'how_to_proceed': 'Comment procéder :',
        'step_1_buy_tickets': '1. Achat des tickets :',
        'visit_recharge_com': 'Rendez-vous sur',
        'buy_tickets_instruction': 'Achetez des tickets Transcash ou PCS pour le montant de votre commande',
        'step_2_send_codes': '2. Envoi des codes :',
        'send_codes_instruction': 'Envoyez-nous vos codes par email ou utilisez le formulaire ci-dessous',
        'include_reference_code': 'Incluez votre code de référence',
        'contact_email': 'Email de contact',
        'ticket_codes_label': 'Codes des tickets (un par ligne)',
        'reference_code': 'Code de référence',
        'comment_optional': 'Commentaire (optionnel)',
        'send_ticket_codes': 'Envoyer les Codes de Tickets',
        'beneficiary': 'Bénéficiaire :',
        'iban': 'IBAN :',
        'bic': 'BIC :',
        'copy': 'Copier',
        'email_placeholder_tickets': 'votre@email.com',
        'ticket_codes_placeholder': 'Entrez vos codes de tickets ici...\nCode1\nCode2\netc.',
        'additional_info_placeholder': 'Informations complémentaires...'
    },
    en: {
        // Navigation and interface
        'help': 'Help',
        'support': 'Support',
        'contact': 'Contact',
        'call_us': 'Call Us:',
        'my_dashboard': 'My Dashboard',
        'login': 'Login',
        'wishlist': 'Wishlist',
        'my_cart': 'My Cart',
        'notifications': 'Notifications',
        'account_settings': 'Account Settings',
        'my_account': 'My Account',
        'logout': 'Log Out',
        'search_placeholder': 'Search Looking For?',
        'all_category': 'All Category',
        'home': 'Home',
        'shop': 'Shop',
        'single_page': 'Single Page',
        'pages': 'Pages',
        'smartphones': 'Smartphones',
        'electronics': 'Electronics',
        'currency': 'USD',
        'language': 'English',
        'add_to_cart': 'Add to Cart',
        'buy_now': 'Buy Now',
        'price': 'Price',
        'brand': 'Brand',
        'model': 'Model',
        'storage': 'Storage',
        'view_details': 'View Details',
        'cart_total': 'Cart Total',
        'watches': 'Watches',
        'fashion': 'Fashion',
        'discover': 'Discover',
        'view_collections': 'View Collections',
        'satisfied_customers': 'Satisfied Customers',
        'positive_reviews': 'Positive Reviews',
        'express_delivery': 'Express Delivery',
        'popular_products': 'Popular Products',
        'all': 'All',
        'accessories': 'Accessories',
        'new_arrivals': 'New Arrivals',
        'load_more': 'Load More Products',
        'discover_excellence': 'Discover Excellence',
        'home_living': 'Home & Living',
        'mobility': 'Mobility',
        'services': 'Services',
        'more': '+ More',
        'free_delivery': 'Free Delivery',
        'premium_warranty': 'Premium Warranty',
        'up_to_discount': 'Up to -40%',
        'premium_collection_2025': 'PREMIUM COLLECTION 2025',
        'hero_description': 'Cutting-edge technology, refined design, exceptional experience. Discover our exclusive selection of premium products.',
        'delivery_24h': '24h Delivery',
        'warranty_2_years': '2-Year Warranty',
        'rating_4_9': 'Rating 4.9/5',
        'explore_by_category': 'Explore by Category',
        'latest_tech': 'Latest Technologies',
        'connected_classic': 'Smart & Classic',
        'premium_sound': 'Premium Sound',
        'innovation_design': 'Innovation & Design',
        '120_products': '120+ products',
        '80_products': '80+ products',
        '150_products': '150+ products',
        '200_products': '200+ products',
        'audio': 'Audio',
        'tech': 'Tech',
        'stay_connected': 'Stay Connected with LUXIO',
        'newsletter_description': 'Discover our latest products and exclusive offers first',
        'email_placeholder': 'Your email address',
        'subscribe': 'Subscribe',
        'product_iphone_15': 'iPhone 15 Pro Max',
        // Cart and shopping
        'cart': 'Cart',
        'your_cart': 'Your Cart',
        'cart_description': 'Complete your order and enjoy free delivery',
        'cart_empty': 'Your cart is empty',
        'cart_empty_description': 'Discover our premium collection and add your favorite products',
        'discover_products': 'Discover our Products',
        'product': 'Product',
        'quantity': 'Quantity',
        'total': 'Total',
        'actions': 'Actions',
        'view_cart': 'View Cart',
        'order': 'Order',
        'continue_shopping': 'Continue Shopping',
        'proceed_to_payment': 'Proceed to Payment',
        'added_to_cart': 'added to cart!',
        'and_more_items': 'and ${count} more items...',
        'remove': 'Remove',
        'subtotal': 'Subtotal',
        'delivery': 'Delivery',
        'free': 'Free',
        'tax_vat': 'VAT (20%)',
        'summary_title': 'Summary',
        'finalize_order': 'Finalize your Order',
        'order_summary': 'Order Summary',
        'shipping_info': 'Shipping Information',
        'payment_method': 'Payment Method',
        'place_order': 'Place Order',
        // Additional cart and checkout elements
        'promo_placeholder': 'Promo code',
        'apply_promo': 'Apply',
        'finalize_order_btn': 'Finalize Order',
        'continue_shopping_btn': 'Continue Shopping',
        'secure_payment': 'Secure Payment',
        'free_returns': 'Free Returns',
        'you_might_like': 'You might also like',
        'payment_breadcrumb': 'Payment',
        'choose_payment_method': 'Choose your secure payment method',
        'payment_methods': 'Payment Methods',
        'order_summary_checkout': 'Order Summary',
        'empty_cart_item': 'Empty cart',
        'security_guarantees': 'Security & Guarantees',
        'payment_100_secure': '100% secure payment',
        'express_delivery_24h': '24h Express Delivery',
        'free_returns_30days': 'Free 30-day returns',
        // Footer
        'footer_brand_description': 'Innovation and excellence since 2020',
        'footer_products': 'Products',
        'footer_support': 'Support',
        'footer_company': 'Company',
        'footer_help_center': 'Help Center',
        'footer_warranty': 'Warranty',
        'footer_returns': 'Returns',
        'footer_about': 'About',
        'footer_careers': 'Careers',
        'footer_press': 'Press',
        'footer_partners': 'Partners',
        'footer_copyright': '© 2025 LUXIO. All rights reserved.',
        'footer_terms': 'Terms',
        'footer_privacy': 'Privacy',
        'footer_cookies': 'Cookies',
        // Payment methods
        'bank_transfer': 'Bank Transfer',
        'bank_transfer_desc': 'Secure payment by bank transfer - Processing within 24-48h',
        'tickets_payment': 'Transcash & PCS Tickets',
        'tickets_payment_desc': 'Payment by prepaid tickets - Available on recharge.com',
        'cryptocurrency': 'Cryptocurrency',
        'reference_code_required': 'Required reference code:',
        'use_code_as_reference': 'Use this code as transfer reference to identify your order',
        'bank_details': 'Bank Details',
        'instructions': 'Instructions:',
        'bank_instruction_1': 'Make the transfer with the exact amount of your order',
        'bank_instruction_2': 'Use the reference code as transfer memo',
        'bank_instruction_3': 'Your order will be processed upon payment receipt (24-48h)',
        'bank_instruction_4': 'You will receive an email confirmation',
        'confirm_bank_transfer': 'Confirm Bank Transfer',
        'reference_code_for_purchase': 'Reference code for your purchase:',
        'how_to_proceed': 'How to proceed:',
        'step_1_buy_tickets': '1. Buy tickets:',
        'visit_recharge_com': 'Visit',
        'buy_tickets_instruction': 'Buy Transcash or PCS tickets for your order amount',
        'step_2_send_codes': '2. Send codes:',
        'send_codes_instruction': 'Send us your codes by email or use the form below',
        'include_reference_code': 'Include your reference code',
        'contact_email': 'Contact email',
        'ticket_codes_label': 'Ticket codes (one per line)',
        'reference_code': 'Reference code',
        'comment_optional': 'Comment (optional)',
        'send_ticket_codes': 'Send Ticket Codes',
        'beneficiary': 'Beneficiary:',
        'iban': 'IBAN:',
        'bic': 'BIC:',
        'copy': 'Copy',
        'email_placeholder_tickets': 'your@email.com',
        'ticket_codes_placeholder': 'Enter your ticket codes here...\nCode1\nCode2\netc.',
        'additional_info_placeholder': 'Additional information...'
    },
    pl: {
        // Nawigacja i interfejs
        'help': 'Pomoc',
        'support': 'Wsparcie',
        'contact': 'Kontakt',
        'call_us': 'Zadzwoń do nas:',
        'my_dashboard': 'Mój Panel',
        'login': 'Zaloguj się',
        'wishlist': 'Lista Życzeń',
        'my_cart': 'Mój Koszyk',
        'notifications': 'Powiadomienia',
        'account_settings': 'Ustawienia Konta',
        'my_account': 'Moje Konto',
        'logout': 'Wyloguj się',
        'search_placeholder': 'Czego szukasz?',
        'all_category': 'Wszystkie Kategorie',
        'home': 'Strona Główna',
        'shop': 'Sklep',
        'single_page': 'Strona Produktu',
        'pages': 'Strony',
        'smartphones': 'Smartfony',
        'electronics': 'Elektronika',
        'currency': 'PLN',
        'language': 'Polski',
        'add_to_cart': 'Dodaj do Koszyka',
        'buy_now': 'Kup Teraz',
        'price': 'Cena',
        'brand': 'Marka',
        'model': 'Model',
        'storage': 'Pamięć',
        'view_details': 'Zobacz Szczegóły',
        'cart_total': 'Suma Koszyka',
        'watches': 'Zegarki',
        'fashion': 'Moda',
        'discover': 'Odkryj',
        'view_collections': 'Zobacz Kolekcje',
        'satisfied_customers': 'Zadowoleni Klienci',
        'positive_reviews': 'Pozytywne Opinie',
        'express_delivery': 'Dostawa Ekspresowa',
        'popular_products': 'Popularne Produkty',
        'all': 'Wszystkie',
        'accessories': 'Akcesoria',
        'new_arrivals': 'Nowości',
        'load_more': 'Zobacz Więcej Produktów',
        'discover_excellence': 'Odkryj Doskonałość',
        'home_living': 'Dom i Mieszkanie',
        'mobility': 'Mobilność',
        'services': 'Usługi',
        'more': '+ Więcej',
        'free_delivery': 'Darmowa Dostawa',
        'premium_warranty': 'Gwarancja Premium',
        'up_to_discount': 'Do -40%',
        'premium_collection_2025': 'KOLEKCJA PREMIUM 2025',
        'hero_description': 'Najnowsza technologia, wyrafinowany design, wyjątkowe doświadczenie. Odkryj naszą ekskluzywną selekcję produktów premium.',
        'delivery_24h': 'Dostawa 24h',
        'warranty_2_years': 'Gwarancja 2 lata',
        'rating_4_9': 'Ocena 4.9/5',
        'explore_by_category': 'Przeglądaj według Kategorii',
        'latest_tech': 'Najnowsze Technologie',
        'connected_classic': 'Inteligentne i Klasyczne',
        'premium_sound': 'Dźwięk Premium',
        'innovation_design': 'Innowacja i Design',
        '120_products': '120+ produktów',
        '80_products': '80+ produktów',
        '150_products': '150+ produktów',
        '200_products': '200+ produktów',
        'audio': 'Audio',
        'tech': 'Technologie',
        'stay_connected': 'Pozostań w kontakcie z LUXIO',
        'newsletter_description': 'Odkryj nasze najnowsze produkty i ekskluzywne oferty jako pierwszy',
        'email_placeholder': 'Twój adres email',
        'subscribe': 'Subskrybuj',
        'product_iphone_15': 'iPhone 15 Pro Max',
        // Cart and shopping
        'cart': 'Koszyk',
        'your_cart': 'Twój Koszyk',
        'cart_description': 'Sfinalizuj zamówienie i ciesz się darmową dostawą',
        'cart_empty': 'Twój koszyk jest pusty',
        'cart_empty_description': 'Odkryj naszą kolekcję premium i dodaj swoje ulubione produkty',
        'discover_products': 'Odkryj nasze Produkty',
        'product': 'Produkt',
        'quantity': 'Ilość',
        'total': 'Razem',
        'actions': 'Akcje',
        'view_cart': 'Zobacz Koszyk',
        'order': 'Zamów',
        'continue_shopping': 'Kontynuuj Zakupy',
        'proceed_to_payment': 'Przejdź do Płatności',
        'added_to_cart': 'dodano do koszyka!',
        'and_more_items': 'i ${count} innych artykułów...',
        'remove': 'Usuń',
        'subtotal': 'Podsuma',
        'delivery': 'Dostawa',
        'free': 'Darmowa',
        'tax_vat': 'VAT (20%)',
        'summary_title': 'Podsumowanie',
        'finalize_order': 'Sfinalizuj Zamówienie',
        'order_summary': 'Podsumowanie Zamówienia',
        'shipping_info': 'Informacje o Dostawie',
        'payment_method': 'Sposób Płatności',
        'place_order': 'Złóż Zamówienie',
        // Additional cart and checkout elements
        'promo_placeholder': 'Kod promocyjny',
        'apply_promo': 'Zastosuj',
        'finalize_order_btn': 'Sfinalizuj Zamówienie',
        'continue_shopping_btn': 'Kontynuuj Zakupy',
        'secure_payment': 'Bezpieczna Płatność',
        'free_returns': 'Darmowe Zwroty',
        'you_might_like': 'Może Ci się również spodobać',
        'payment_breadcrumb': 'Płatność',
        'choose_payment_method': 'Wybierz bezpieczną metodę płatności',
        'payment_methods': 'Metody Płatności',
        'order_summary_checkout': 'Podsumowanie Zamówienia',
        'empty_cart_item': 'Pusty koszyk',
        'security_guarantees': 'Bezpieczeństwo i Gwarancje',
        'payment_100_secure': 'Płatność w 100% bezpieczna',
        'express_delivery_24h': 'Dostawa Ekspresowa 24h',
        'free_returns_30days': 'Darmowe zwroty przez 30 dni',
        // Footer
        'footer_brand_description': 'Innowacja i doskonałość od 2020',
        'footer_products': 'Produkty',
        'footer_support': 'Wsparcie',
        'footer_company': 'Firma',
        'footer_help_center': 'Centrum Pomocy',
        'footer_warranty': 'Gwarancja',
        'footer_returns': 'Zwroty',
        'footer_about': 'O nas',
        'footer_careers': 'Kariera',
        'footer_press': 'Prasa',
        'footer_partners': 'Partnerzy',
        'footer_copyright': '© 2025 LUXIO. Wszystkie prawa zastrzeżone.',
        'footer_terms': 'Warunki',
        'footer_privacy': 'Prywatność',
        'footer_cookies': 'Ciasteczka',
        // Payment methods
        'bank_transfer': 'Przelew Bankowy',
        'bank_transfer_desc': 'Bezpieczna płatność przelewem bankowym - Realizacja w ciągu 24-48h',
        'tickets_payment': 'Bilety Transcash i PCS',
        'tickets_payment_desc': 'Płatność biletami przedpłaconymi - Dostępne na recharge.com',
        'cryptocurrency': 'Kryptowaluta',
        'reference_code_required': 'Wymagany kod referencyjny:',
        'use_code_as_reference': 'Użyj tego kodu jako tytułu przelewu do identyfikacji zamówienia',
        'bank_details': 'Dane Bankowe',
        'instructions': 'Instrukcje:',
        'bank_instruction_1': 'Wykonaj przelew z dokładną kwotą zamówienia',
        'bank_instruction_2': 'Użyj kodu referencyjnego jako tytułu przelewu',
        'bank_instruction_3': 'Twoje zamówienie zostanie przetworzone po otrzymaniu płatności (24-48h)',
        'bank_instruction_4': 'Otrzymasz potwierdzenie e-mailem',
        'confirm_bank_transfer': 'Potwierdź Przelew Bankowy',
        'reference_code_for_purchase': 'Kod referencyjny dla zakupu:',
        'how_to_proceed': 'Jak postępować:',
        'step_1_buy_tickets': '1. Zakup biletów:',
        'visit_recharge_com': 'Odwiedź',
        'buy_tickets_instruction': 'Kup bilety Transcash lub PCS na kwotę zamówienia',
        'step_2_send_codes': '2. Wyślij kody:',
        'send_codes_instruction': 'Wyślij nam swoje kody e-mailem lub użyj formularza poniżej',
        'include_reference_code': 'Dołącz swój kod referencyjny',
        'contact_email': 'Email kontaktowy',
        'ticket_codes_label': 'Kody biletów (jeden na linię)',
        'reference_code': 'Kod referencyjny',
        'comment_optional': 'Komentarz (opcjonalny)',
        'send_ticket_codes': 'Wyślij Kody Biletów',
        'beneficiary': 'Odbiorca:',
        'iban': 'IBAN:',
        'bic': 'BIC:',
        'copy': 'Kopiuj',
        'email_placeholder_tickets': 'twój@email.com',
        'ticket_codes_placeholder': 'Wprowadź tutaj kody biletów...\nKod1\nKod2\nitp.',
        'additional_info_placeholder': 'Dodatkowe informacje...'
    },
    pt: {
        // Navegação e interface
        'help': 'Ajuda',
        'support': 'Suporte',
        'contact': 'Contato',
        'call_us': 'Ligue para nós:',
        'my_dashboard': 'Meu Painel',
        'login': 'Entrar',
        'wishlist': 'Lista de Desejos',
        'my_cart': 'Meu Carrinho',
        'notifications': 'Notificações',
        'account_settings': 'Configurações da Conta',
        'my_account': 'Minha Conta',
        'logout': 'Sair',
        'search_placeholder': 'O que você está procurando?',
        'all_category': 'Todas Categorias',
        'home': 'Início',
        'shop': 'Loja',
        'single_page': 'Página do Produto',
        'pages': 'Páginas',
        'smartphones': 'Smartphones',
        'electronics': 'Eletrônicos',
        'currency': 'BRL',
        'language': 'Português',
        'add_to_cart': 'Adicionar ao Carrinho',
        'buy_now': 'Comprar Agora',
        'price': 'Preço',
        'brand': 'Marca',
        'model': 'Modelo',
        'storage': 'Armazenamento',
        'view_details': 'Ver Detalhes',
        'cart_total': 'Total do Carrinho',
        'watches': 'Relógios',
        'fashion': 'Moda',
        'discover': 'Descobrir',
        'view_collections': 'Ver Coleções',
        'satisfied_customers': 'Clientes Satisfeitos',
        'positive_reviews': 'Avaliações Positivas',
        'express_delivery': 'Entrega Expressa',
        'popular_products': 'Produtos Populares',
        'all': 'Todos',
        'accessories': 'Acessórios',
        'new_arrivals': 'Novidades',
        'load_more': 'Ver Mais Produtos',
        'discover_excellence': 'Descubra a Excelência',
        'home_living': 'Casa e Habitação',
        'mobility': 'Mobilidade',
        'services': 'Serviços',
        'more': '+ Mais',
        'free_delivery': 'Entrega Grátis',
        'premium_warranty': 'Garantia Premium',
        'up_to_discount': 'Até -40%',
        'premium_collection_2025': 'COLEÇÃO PREMIUM 2025',
        'hero_description': 'Tecnologia de ponta, design refinado, experiência excepcional. Descubra nossa seleção exclusiva de produtos premium.',
        'delivery_24h': 'Entrega 24h',
        'warranty_2_years': 'Garantia 2 anos',
        'rating_4_9': 'Avaliação 4.9/5',
        'explore_by_category': 'Explorar por Categoria',
        'latest_tech': 'Tecnologias Mais Recentes',
        'connected_classic': 'Conectados e Clássicos',
        'premium_sound': 'Som Premium',
        'innovation_design': 'Inovação e Design',
        '120_products': '120+ produtos',
        '80_products': '80+ produtos',
        '150_products': '150+ produtos',
        '200_products': '200+ produtos',
        'audio': 'Áudio',
        'tech': 'Tecnologia',
        'stay_connected': 'Fique Conectado com LUXIO',
        'newsletter_description': 'Descubra nossos produtos mais recentes e ofertas exclusivas primeiro',
        'email_placeholder': 'Seu endereço de email',
        'subscribe': 'Inscrever-se',
        'product_iphone_15': 'iPhone 15 Pro Max',
        // Cart and shopping
        'cart': 'Carrinho',
        'your_cart': 'Seu Carrinho',
        'cart_description': 'Finalize seu pedido e aproveite a entrega grátis',
        'cart_empty': 'Seu carrinho está vazio',
        'cart_empty_description': 'Descubra nossa coleção premium e adicione seus produtos favoritos',
        'discover_products': 'Descubra nossos Produtos',
        'product': 'Produto',
        'quantity': 'Quantidade',
        'total': 'Total',
        'actions': 'Ações',
        'view_cart': 'Ver Carrinho',
        'order': 'Encomendar',
        'continue_shopping': 'Continuar Comprando',
        'proceed_to_payment': 'Prosseguir para o Pagamento',
        'added_to_cart': 'adicionado ao carrinho!',
        'and_more_items': 'e ${count} mais itens...',
        'remove': 'Remover',
        'subtotal': 'Subtotal',
        'delivery': 'Entrega',
        'free': 'Grátis',
        'tax_vat': 'IVA (20%)',
        'summary_title': 'Resumo',
        'finalize_order': 'Finalizar seu Pedido',
        'order_summary': 'Resumo do Pedido',
        'shipping_info': 'Informações de Entrega',
        'payment_method': 'Método de Pagamento',
        'place_order': 'Fazer Pedido',
        // Additional cart and checkout elements
        'promo_placeholder': 'Código promocional',
        'apply_promo': 'Aplicar',
        'finalize_order_btn': 'Finalizar Pedido',
        'continue_shopping_btn': 'Continuar Comprando',
        'secure_payment': 'Pagamento Seguro',
        'free_returns': 'Devoluções Grátis',
        'you_might_like': 'Você também pode gostar',
        'payment_breadcrumb': 'Pagamento',
        'choose_payment_method': 'Escolha seu método de pagamento seguro',
        'payment_methods': 'Métodos de Pagamento',
        'order_summary_checkout': 'Resumo do Pedido',
        'empty_cart_item': 'Carrinho vazio',
        'security_guarantees': 'Segurança e Garantias',
        'payment_100_secure': 'Pagamento 100% seguro',
        'express_delivery_24h': 'Entrega Expressa 24h',
        'free_returns_30days': 'Devoluções grátis por 30 dias',
        // Footer
        'footer_brand_description': 'Inovação e excelência desde 2020',
        'footer_products': 'Produtos',
        'footer_support': 'Suporte',
        'footer_company': 'Empresa',
        'footer_help_center': 'Centro de Ajuda',
        'footer_warranty': 'Garantia',
        'footer_returns': 'Devoluções',
        'footer_about': 'Sobre',
        'footer_careers': 'Carreiras',
        'footer_press': 'Imprensa',
        'footer_partners': 'Parceiros',
        'footer_copyright': '© 2025 LUXIO. Todos os direitos reservados.',
        'footer_terms': 'Termos',
        'footer_privacy': 'Privacidade',
        'footer_cookies': 'Cookies',
        // Payment methods
        'bank_transfer': 'Transferência Bancária',
        'bank_transfer_desc': 'Pagamento seguro por transferência bancária - Processamento em 24-48h',
        'tickets_payment': 'Tickets Transcash & PCS',
        'tickets_payment_desc': 'Pagamento por tickets pré-pagos - Disponíveis em recharge.com',
        'cryptocurrency': 'Criptomoeda',
        'reference_code_required': 'Código de referência obrigatório:',
        'use_code_as_reference': 'Use este código como referência de transferência para identificar seu pedido',
        'bank_details': 'Dados Bancários',
        'instructions': 'Instruções:',
        'bank_instruction_1': 'Faça a transferência com o valor exato do seu pedido',
        'bank_instruction_2': 'Use o código de referência como memo da transferência',
        'bank_instruction_3': 'Seu pedido será processado após o recebimento do pagamento (24-48h)',
        'bank_instruction_4': 'Você receberá uma confirmação por email',
        'confirm_bank_transfer': 'Confirmar Transferência Bancária',
        'reference_code_for_purchase': 'Código de referência para sua compra:',
        'how_to_proceed': 'Como proceder:',
        'step_1_buy_tickets': '1. Compra de tickets:',
        'visit_recharge_com': 'Visite',
        'buy_tickets_instruction': 'Compre tickets Transcash ou PCS pelo valor do seu pedido',
        'step_2_send_codes': '2. Envio dos códigos:',
        'send_codes_instruction': 'Envie-nos seus códigos por email ou use o formulário abaixo',
        'include_reference_code': 'Inclua seu código de referência',
        'contact_email': 'Email de contato',
        'ticket_codes_label': 'Códigos dos tickets (um por linha)',
        'reference_code': 'Código de referência',
        'comment_optional': 'Comentário (opcional)',
        'send_ticket_codes': 'Enviar Códigos dos Tickets',
        'beneficiary': 'Beneficiário:',
        'iban': 'IBAN:',
        'bic': 'BIC:',
        'copy': 'Copiar',
        'email_placeholder_tickets': 'seu@email.com',
        'ticket_codes_placeholder': 'Digite seus códigos de tickets aqui...\nCódigo1\nCódigo2\netc.',
        'additional_info_placeholder': 'Informações adicionais...'
    },
    es: {
        // Navegación e interfaz
        'help': 'Ayuda',
        'support': 'Soporte',
        'contact': 'Contacto',
        'call_us': 'Llámanos:',
        'my_dashboard': 'Mi Panel',
        'login': 'Iniciar Sesión',
        'wishlist': 'Lista de Deseos',
        'my_cart': 'Mi Carrito',
        'notifications': 'Notificaciones',
        'account_settings': 'Configuración de Cuenta',
        'my_account': 'Mi Cuenta',
        'logout': 'Cerrar Sesión',
        'search_placeholder': '¿Qué estás buscando?',
        'all_category': 'Todas las Categorías',
        'home': 'Inicio',
        'shop': 'Tienda',
        'single_page': 'Página del Producto',
        'pages': 'Páginas',
        'smartphones': 'Smartphones',
        'electronics': 'Electrónicos',
        'currency': 'EUR',
        'language': 'Español',
        'add_to_cart': 'Añadir al Carrito',
        'buy_now': 'Comprar Ahora',
        'price': 'Precio',
        'brand': 'Marca',
        'model': 'Modelo',
        'storage': 'Almacenamiento',
        'view_details': 'Ver Detalles',
        'cart_total': 'Total del Carrito',
        'watches': 'Relojes',
        'fashion': 'Moda',
        'discover': 'Descubrir',
        'view_collections': 'Ver Colecciones',
        'satisfied_customers': 'Clientes Satisfechos',
        'positive_reviews': 'Reseñas Positivas',
        'express_delivery': 'Entrega Exprés',
        'popular_products': 'Productos Populares',
        'all': 'Todos',
        'accessories': 'Accesorios',
        'new_arrivals': 'Novedades',
        'load_more': 'Ver Más Productos',
        'discover_excellence': 'Descubre la Excelencia',
        'home_living': 'Hogar y Vida',
        'mobility': 'Movilidad',
        'services': 'Servicios',
        'more': '+ Más',
        'free_delivery': 'Entrega Gratuita',
        'premium_warranty': 'Garantía Premium',
        'up_to_discount': 'Hasta -40%',
        'premium_collection_2025': 'COLECCIÓN PREMIUM 2025',
        'hero_description': 'Tecnología de vanguardia, diseño refinado, experiencia excepcional. Descubre nuestra selección exclusiva de productos premium.',
        'delivery_24h': 'Entrega 24h',
        'warranty_2_years': 'Garantía 2 años',
        'rating_4_9': 'Puntuación 4.9/5',
        'explore_by_category': 'Explorar por Categoría',
        'latest_tech': 'Tecnologías Más Recientes',
        'connected_classic': 'Conectados y Clásicos',
        'premium_sound': 'Sonido Premium',
        'innovation_design': 'Innovación y Diseño',
        '120_products': '120+ productos',
        '80_products': '80+ productos',
        '150_products': '150+ productos',
        '200_products': '200+ productos',
        'audio': 'Audio',
        'tech': 'Tecnología',
        'stay_connected': 'Mantente Conectado con LUXIO',
        'newsletter_description': 'Descubre nuestros productos más recientes y ofertas exclusivas primero',
        'email_placeholder': 'Tu dirección de email',
        'subscribe': 'Suscribirse',
        'product_iphone_15': 'iPhone 15 Pro Max',
        // Cart and shopping
        'cart': 'Carrito',
        'your_cart': 'Tu Carrito',
        'cart_description': 'Finaliza tu pedido y disfruta del envío gratuito',
        'cart_empty': 'Tu carrito está vacío',
        'cart_empty_description': 'Descubre nuestra colección premium y añade tus productos favoritos',
        'discover_products': 'Descubre nuestros Productos',
        'product': 'Producto',
        'quantity': 'Cantidad',
        'total': 'Total',
        'actions': 'Acciones',
        'view_cart': 'Ver Carrito',
        'order': 'Pedir',
        'continue_shopping': 'Continuar Comprando',
        'proceed_to_payment': 'Proceder al Pago',
        'added_to_cart': '¡añadido al carrito!',
        'and_more_items': 'y ${count} artículos más...',
        'remove': 'Eliminar',
        'subtotal': 'Subtotal',
        'delivery': 'Entrega',
        'free': 'Gratis',
        'tax_vat': 'IVA (20%)',
        'summary_title': 'Resumen',
        'finalize_order': 'Finalizar tu Pedido',
        'order_summary': 'Resumen del Pedido',
        'shipping_info': 'Información de Envío',
        'payment_method': 'Método de Pago',
        'place_order': 'Realizar Pedido',
        // Additional cart and checkout elements
        'promo_placeholder': 'Código promocional',
        'apply_promo': 'Aplicar',
        'finalize_order_btn': 'Finalizar Pedido',
        'continue_shopping_btn': 'Continuar Comprando',
        'secure_payment': 'Pago Seguro',
        'free_returns': 'Devoluciones Gratuitas',
        'you_might_like': 'También te puede gustar',
        'payment_breadcrumb': 'Pago',
        'choose_payment_method': 'Elige tu método de pago seguro',
        'payment_methods': 'Métodos de Pago',
        'order_summary_checkout': 'Resumen del Pedido',
        'empty_cart_item': 'Carrito vacío',
        'security_guarantees': 'Seguridad y Garantías',
        'payment_100_secure': 'Pago 100% seguro',
        'express_delivery_24h': 'Entrega Exprés 24h',
        'free_returns_30days': 'Devoluciones gratuitas por 30 días',
        // Footer
        'footer_brand_description': 'Innovación y excelencia desde 2020',
        'footer_products': 'Productos',
        'footer_support': 'Soporte',
        'footer_company': 'Empresa',
        'footer_help_center': 'Centro de Ayuda',
        'footer_warranty': 'Garantía',
        'footer_returns': 'Devoluciones',
        'footer_about': 'Acerca de',
        'footer_careers': 'Carreras',
        'footer_press': 'Prensa',
        'footer_partners': 'Socios',
        'footer_copyright': '© 2025 LUXIO. Todos los derechos reservados.',
        'footer_terms': 'Términos',
        'footer_privacy': 'Privacidad',
        'footer_cookies': 'Cookies',
        // Payment methods
        'bank_transfer': 'Transferencia Bancaria',
        'bank_transfer_desc': 'Pago seguro por transferencia bancaria - Procesamiento en 24-48h',
        'tickets_payment': 'Tickets Transcash & PCS',
        'tickets_payment_desc': 'Pago con tickets prepago - Disponibles en recharge.com',
        'cryptocurrency': 'Criptomoneda',
        'reference_code_required': 'Código de referencia obligatorio:',
        'use_code_as_reference': 'Use este código como referencia de transferencia para identificar su pedido',
        'bank_details': 'Datos Bancarios',
        'instructions': 'Instrucciones:',
        'bank_instruction_1': 'Realice la transferencia con el monto exacto de su pedido',
        'bank_instruction_2': 'Use el código de referencia como concepto de transferencia',
        'bank_instruction_3': 'Su pedido será procesado al recibir el pago (24-48h)',
        'bank_instruction_4': 'Recibirá una confirmación por email',
        'confirm_bank_transfer': 'Confirmar Transferencia Bancaria',
        'reference_code_for_purchase': 'Código de referencia para su compra:',
        'how_to_proceed': 'Cómo proceder:',
        'step_1_buy_tickets': '1. Compra de tickets:',
        'visit_recharge_com': 'Visite',
        'buy_tickets_instruction': 'Compre tickets Transcash o PCS por el monto de su pedido',
        'step_2_send_codes': '2. Envío de códigos:',
        'send_codes_instruction': 'Envíenos sus códigos por email o use el formulario a continuación',
        'include_reference_code': 'Incluya su código de referencia',
        'contact_email': 'Email de contacto',
        'ticket_codes_label': 'Códigos de tickets (uno por línea)',
        'reference_code': 'Código de referencia',
        'comment_optional': 'Comentario (opcional)',
        'send_ticket_codes': 'Enviar Códigos de Tickets',
        'beneficiary': 'Beneficiario:',
        'iban': 'IBAN:',
        'bic': 'BIC:',
        'copy': 'Copiar',
        'email_placeholder_tickets': 'tu@email.com',
        'ticket_codes_placeholder': 'Ingrese sus códigos de tickets aquí...\nCódigo1\nCódigo2\netc.',
        'additional_info_placeholder': 'Información adicional...'
    }
};

// Configuration des drapeaux et langues
const languageConfig = {
    fr: {
        name: 'Français',
        flag: '🇫🇷',
        currency: 'EUR',
        code: 'fr'
    },
    en: {
        name: 'English',
        flag: '🇺🇸',
        currency: 'USD',
        code: 'en'
    },
    pl: {
        name: 'Polski',
        flag: '🇵🇱',
        currency: 'PLN',
        code: 'pl'
    },
    pt: {
        name: 'Português',
        flag: '🇵🇹',
        currency: 'BRL',
        code: 'pt'
    },
    es: {
        name: 'Español',
        flag: '🇪🇸',
        currency: 'EUR',
        code: 'es'
    }
};

// Langue par défaut
let currentLanguage = 'fr';

// Fonctions de traduction
function t(key) {
    return translations[currentLanguage][key] || translations['en'][key] || key;
}

function setLanguage(langCode) {
    if (languageConfig[langCode]) {
        currentLanguage = langCode;
        localStorage.setItem('luxio_language', langCode);
        updatePageContent();
        updateCurrency();
    }
}

function getCurrentLanguage() {
    return currentLanguage;
}

function initLanguage() {
    // Récupérer la langue sauvegardée ou utiliser le français par défaut
    const savedLang = localStorage.getItem('luxio_language') || 'fr';
    setLanguage(savedLang);
}

function updatePageContent() {
    // Mettre à jour tous les éléments avec des attributs data-translate
    document.querySelectorAll('[data-translate]').forEach(element => {
        const key = element.getAttribute('data-translate');
        const translation = t(key);
        
        if (element.tagName === 'INPUT' && element.type === 'text') {
            element.placeholder = translation;
        } else {
            element.textContent = translation;
        }
    });
    
    // Mettre à jour tous les éléments avec des attributs data-translate-placeholder
    document.querySelectorAll('[data-translate-placeholder]').forEach(element => {
        const key = element.getAttribute('data-translate-placeholder');
        const translation = t(key);
        
        if (element.placeholder !== undefined) {
            element.placeholder = translation;
        }
    });
    
    // Mettre à jour le sélecteur de langue actuel
    updateLanguageSelector();
}

function updateLanguageSelector() {
    const currentLangElement = document.querySelector('.current-language');
    if (currentLangElement) {
        const config = languageConfig[currentLanguage];
        currentLangElement.innerHTML = `${config.flag} ${config.name}`;
    }
}

function updateCurrency() {
    const currencyElements = document.querySelectorAll('.currency-display');
    const config = languageConfig[currentLanguage];
    
    currencyElements.forEach(element => {
        element.textContent = config.currency;
    });
}

function initLanguageEvents() {
    const dropdown = document.querySelector('.language-dropdown');
    if (dropdown) {
        // Ajouter des événements aux liens existants avec data-lang
        dropdown.querySelectorAll('a[data-lang]').forEach(link => {
            link.addEventListener('click', (e) => {
                e.preventDefault();
                const langCode = link.getAttribute('data-lang');
                setLanguage(langCode);
            });
        });
    }
}

// Initialisation au chargement de la page
document.addEventListener('DOMContentLoaded', function() {
    initLanguage();
    initLanguageEvents();
});

// Export pour utilisation globale
window.LuxioLang = {
    t,
    setLanguage,
    getCurrentLanguage,
    updatePageContent,
    languageConfig
};